# Model parameters
name: 'CNN'
max_num_sources: 4
sequence_duration: 30
num_fft_bins: 2048
frame_length: 0.04
chunk_length: 0.5
dropout_rate: 0
learning_rate: 0.05
num_epochs_warmup: 5
gradient_clip_val: 1.0
alpha: 1

# Experimental setup
dataset: [ansim, resim, real]
max_epochs: 200
manual_seed: 1234
